// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNpe2QlZG_-aKbmWwm03OY-18B_9f7Vv0',
    appId: '1:544134864661:android:6b3057d58fbc475706531c',
    messagingSenderId: '544134864661',
    projectId: 'chatbot-2fd14',
    storageBucket: 'chatbot-2fd14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3DUKh61H-pRZgemM6bHJJcN2w2jhNsSE',
    appId: '1:544134864661:ios:ee2e2c12d45cd39206531c',
    messagingSenderId: '544134864661',
    projectId: 'chatbot-2fd14',
    storageBucket: 'chatbot-2fd14.firebasestorage.app',
    iosBundleId: 'com.example.robotProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3DUKh61H-pRZgemM6bHJJcN2w2jhNsSE',
    appId: '1:544134864661:ios:ee2e2c12d45cd39206531c',
    messagingSenderId: '544134864661',
    projectId: 'chatbot-2fd14',
    storageBucket: 'chatbot-2fd14.firebasestorage.app',
    iosBundleId: 'com.example.robotProject',
  );
}
